#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
  :git => 'https://github.com/opscode-cookbooks/git',
  :ref => '2.5.2'

cookbook 'application',
  :git => 'https://github.com/opscode-cookbooks/application',
  :ref => '3.0.0'
  
cookbook 'application_php',
  :git => 'https://github.com/opscode-cookbooks/application_php',
  :ref => '2.0.0'
  
cookbook 'php_app',
  :git => 'https://github.com/flaccid/cookbooks',
  :path => 'cookbooks/php_app',
  :ref => 'master'

cookbook 'system',
  :git => 'https://github.com/flaccid/cookbooks',
  :path => 'cookbooks/system',
  :ref => 'master'

